### ISSUE TITLE
start.sh: line 27: [RAK2245: command not found

### ISSUE THREAD

**Issue by fraterv** [balenalabs/basicstation#12]
I pulled the latest version this morning. I deployed it to two gateways but when the container comes up, it fails with the following message:

```
03.02.21 10:19:51 (+0100)  main  xxxxxxFFFExxxxx
03.02.21 10:19:52 (+0100)  main  Using MODEL: RAK2245
03.02.21 10:19:52 (+0100)  main  start.sh: line 27: [RAK2245: command not found
03.02.21 10:19:53 (+0100) Service exited 'main sha256:36af82b74f0f007d547cc4b1effcb51f264815590a7575c1f1bb6e5c7c5166a4'
```

As mentioned in the docu, I have set the MODEL variable to RAK2245 in the device configuration. But it seems something is wrong with the start script. I'm at work now, so I can't investigate further at the moment.

**Comment by carlrakwireless** [comment]
also happening to me.

**Comment by fraterv** [comment]
In line 27 of `startup.sh` there is a | missing. Which means the logical "or" is broken. It should be two || :

`if [ $MODEL = "RAK2245" ] || [$MODEL = "iC880a"];then`

**Comment by mpous** [comment]
Thank you @jmarcelino
